freeglut/freeglut

freeglut/freeglut/CMakeLists.txt, freeglut/freeglut/src/egl/fg_init_egl.c, freeglut/freeglut/src/fg_internal.h, freeglut/freeglut/src/wayland/fg_cursor_wl.c, freeglut/freeglut/src/wayland/fg_ext_wl.c, freeglut/freeglut/src/wayland/fg_gamemode_wl.c, freeglut/freeglut/src/wayland/fg_init_wl.c, freeglut/freeglut/src/wayland/fg_input_devices_wl.c, freeglut/freeglut/src/wayland/fg_internal_wl.h, freeglut/freeglut/src/wayland/fg_main_wl.c, freeglut/freeglut/src/wayland/fg_state_wl.c, freeglut/freeglut/src/wayland/fg_structure_wl.c, freeglut/freeglut/src/wayland/fg_window_wl.c
This commit creates a new "wayland" backend, which can be
activated at configure time with "-DFREEGLUT_WAYLAND=ON".
If done so, it will be used instead of X11 (building both
and doing runtime detection may become possible later).
Please note that if you choose to use GL instead of GLES
(by not specifying "-DFREEGLUT_GLES=ON"), then libX11
will still be pulled as an indirect dependency.
Following features are still WIP :
- menus (not implemented, TODO) ;
- client-side decorations (not implemented, required
because Wayland shells do not draw title bars nor
resize grips, TODO) ;
- game mode (code is commented out, depends on WIP
protocols tested upstream, WAIT FOR UPSTREAM) ;
- window visibility states (code is commented out,
depends on xdg-shell protocol, TODO).
Signed-off-by: Manuel …
=> Implement initial Wayland support

freeglut/freeglut/src/fg_spaceball.c
Commit ce15044f7362943aee7d465bf20310ba02991dae introduced an error
"undefined reference to `sball_initialized'" on non-Windows operating
systems.
=> Fix compilation on Linux.

freeglut/freeglut/CMakeLists.txt
Irrespective of "FREEGLUT_REPLACE_GLUT" being set to "No" or being on
Win32 where this variable does not even exist, the .pc file contained
Libs: -L${libdir} -lglut
Instead, emit the correct value.
=> Emit the correct LIBNAME to .pc files

freeglut/freeglut/CMakeLists.txt
The CMake variable "MSVC" indicates that the Visual Studio compiler is
used but  when using that compiler and the "NMake Makefiles JOM" build
generator the *.pdb is wasn't output in a "Debug" directory.
=> Fixed freeglut.pdb install for builds with MSVC compiler and NMake.

freeglut/freeglut/CMakeLists.txt
Tested with Android NDK r16b using
`-DCMAKE_TOOLCHAIN_FILE="${ANDROID_NDK_ROOT}/build/cmake/android.toolchain.cmake"`.
(See [aplump](https://github.com/sibuserv/aplump) project, if interested.)
=> Fix build for Android using clang compiler.

freeglut/freeglut/src/wayland/fg_internal_wl.h, freeglut/freeglut/src/x11/fg_internal_x11.h
<machine/joystick.h> is a compatibility header that only includes
<sys/joystick.h>, and wasn't added to newer architectures.
This helps the build on netbsd/aarch64.
=> Use <sys/joystick.h> on netbsd, too.

mingw_cross_toolchain.cmake
I must say I don't know what the `Prefix detection only works with compiler id "GNU"` was about, but it was there since 2012, and it seems not needed any longer.
I have tested the resulting libglut.dll on Windows 10 (with libfreenect-glview).
=> mingw_cross: Add C++ compiler and remove deprecated CMakeForceCompiler

src/x11/fg_glutfont_definitions_x11.c
Noticed when compiling with link-time optimizations.
````
include/GL/freeglut_std.h:240:18: error: type of ‘glutBitmapHelvetica18’ does not match original declaration [-Werror=lto-type-mismatch]
240 |     extern void* glutBitmapHelvetica18;
|                  ^
src/x11/fg_glutfont_definitions_x11.c:103:27: note: ‘glutBitmapHelvetica18’ was previously declared here
103 | struct freeglutBitmapFont glutBitmapHelvetica18 ;
|                           ^
src/x11/fg_glutfont_definitions_x11.c:103:27: note: code may be misoptimized unless ‘-fno-strict-aliasing’ is used
````
=> Fix aliasing violation

src/gles_stubs.c
```
In file included from c:\gcc1130\x86_64-w64-mingw32\include\gl\freeglut_ext.h:287,
from c:\gcc1130\x86_64-w64-mingw32\include\gl\freeglut.h:18,
from gles_stubs.c:4:
gles_stubs.c:22:16: error: redefinition of 'glutCreateMenuUcall_ATEXIT_HACK'
22 | int FGAPIENTRY glutCreateMenuUcall( FGCBMenuUC callback, FGCBUserData userData ) { return 0; }
|                ^~~~~~~~~~~~~~~~~~~
c:\gcc1130\x86_64-w64-mingw32\include\gl\freeglut_ucall.h:101:32: note: previous definition of 'glutCreateMenuUcall_ATEXIT_HACK' with type 'int(void (*)(int,  void *), void *)'
101 | static int FGAPIENTRY FGUNUSED glutCreateMenuUcall_ATEXIT_HACK(void(*func)(int, void*), void* user_data) { return __glutCreateMenuUcallWithExit(func, exit, user_data); }
| …
```
=> Added FREEGLUT_BUILDING_LIB for GCC 11.3.0

src/mswin/fg_main_mswin.c, src/mswin/fg_window_mswin.c
These double casts remove warning `C4312 conversion from 'unsigned int' to '<>' of greater size`, which previously showed up when compiling on 64-bit windows.
=> Remving WIN64 compiler warnings.

CMakeLists.txt
Currently, the CMakeLists.txt file assumes CL_64 == x64, which means static lib builds (such as in blender) are broken on ARM64 target platforms. This makes a check for this, which allows the build to succeed.
=> Add support for ARM64 MSVC targets

src/x11/fg_joystick_x11.c
fghJoystickRawRead changed name to fgJoystickRawRead but all uses of fghJoystickRawRead were not changed. This caused trouble on illumos/solaris when building and linking freeglut.
Fixes issue #149 .
=> fghJoystickRawRead -> fgJoystickRawRead in solaris code

CMakeLists.txt
FreeGLUT doesn't properly link against the GLU library. It specifies a dependency on the GLU library for the demos. This is not accurate, as it uses the glu.h include. The OpenGL::GLU target or library should be linked against explicitly. The include directory for the GLU library also needs to be handled. CMake's FindOpenGL didn't properly search for the glu.h header file until very recently. Refer to this PR: https://gitlab.kitware.com/cmake/cmake/-/merge_requests/9216.
This PR links to the OpenGL::GLU target where it is available. Where the target isn't available, it links against the library and adds the include directory. For versions of CMake prior to 3.29, the include directory for GLU is added even when linking against the OpenGL::GLU target. Like the FindOpenGL module, GLU include …
=> Incorporate the include directory for glu.h in CMake

src/fg_menu.c
If fgStructure.CurrentMenu is set when glutAddMenuEntry() or glutAddSubMenu() is called the allocated menuEntry variable will leak. This commit postpones allocating menuEntry until after the error checks, thereby plugging the memory leak.
This fixes CVE-2024-24258 and CVE-2024-24259.
=> Plug memory leak that happens upon error.

src/fg_internal.h, src/fg_joystick.c
=> Let platforms override the maximum number of joysticks

CMakeLists.txt, README.ogc, src/fg_internal.h, src/ogc/fg_common_ogc.h, src/ogc/fg_cursor_ogc.c, src/ogc/fg_display_ogc.c, src/ogc/fg_ext_ogc.c, src/ogc/fg_gamemode_ogc.c, src/ogc/fg_init_ogc.c, src/ogc/fg_input_devices_ogc.c, src/ogc/fg_internal_ogc.h, src/ogc/fg_joystick_ogc.c, src/ogc/fg_main_ogc.c, src/ogc/fg_state_ogc.c, src/ogc/fg_structure_ogc.c, src/ogc/fg_window_ogc.c
Depends on https://github.com/freeglut/freeglut/pull/165
Add a backend for the Nintendo Wii and GameCube consoles. Video, joysticks, keyboard and mouse (emulated using the Wiimote infrared pointer) work. I don't foresee the need to work on other features (though I might submit another PR later to draw the mouse cursor), but I will consider them if someone requests them.
And indeed, I volunteer to maintain this backend and to respond to bug reports as promptly as possible.
This PR is split in two commits, one where the backend is added as a stub, the other with the real implementation. Feel free to squash them, if you like (though keeping them separate might be of help to someone willing to write a new backend, because they could be used as a template).
=> Add backend for Nintendo Wii/GameCube 

src/ogc/fg_display_ogc.c
Without this, the screen shows green for a couple of seconds while the application starts.
=> ogc: clear frame buffer when setting a video mode

CMakeLists.txt
It was listing X11 libraries, which we obviously don't have on the GameCube/Wii.
=> ogc: fix the Libs.private entry in the glut.pc file

src/ogc/fg_cursor_ogc.c
If neither glutMotionFunc() or glutMouseFunc() were called, we can safely assume that the application is not interested in mouse events. In this case, it's better to hide the mouse cursor otherwise the user might be led to think that mouse interaction is somehow possible.
=> ogc: don't show the mouse cursor if no callbacks were registered

src/ogc/fg_display_ogc.c
This is needed in order to support the GL_SELECT rendering mode (in that case, ogx_prepare_swap_buffers() will return a negative number), and generally to let opengx restore the embedded frame buffer state, in case it had been setup in some special mode.
=> ogc: let opengx know that we are about to swap buffers

src/ogc/fg_display_ogc.c
This fixes an implicit declaration warning.
=> ogc: add missing include

src/ogc/fg_main_ogc.c
This fixes an issue where applications which did not register an idle callback would stall for 30+ seconds, since we don't have a callback that would wake us up from the sleep.
=> ogc: reduce sleep time if the mouse is being polled

src/ogc/fg_main_ogc.c, src/ogc/fg_window_ogc.c
Our window is always visible, so emit the callback as soon as a window is created.
=> ogc: invoke visibility callback

src/ogc/fg_display_ogc.c, src/ogc/fg_state_ogc.c
If a stencil buffer was requested, tell opengx to create it.
=> freeglut: enable stencil in opengx

CMakeLists.txt
This condition was added when we first added support for the GameCube & Wii consoles because at that time the opengx library did not support glBitmap(). Now that support is there, these files build just fine.
(I verified that fonts do get pronted correctly, as for menus I didn't find a suitable test yet -- but since they just use basic GL functions, I assume they should be working too)
=> build: revert GameCube/Wii hack

src/egl/fg_init_egl.h
C23 removes unprototyped functions, so this conflicted with the definition in fg_init_x11.c.
Bug: https://github.com/freeglut/freeglut/issues/186
=> egl: fix fgPlatformDestroyContext prototype for C23

include/GL/freeglut_std.h
This fixes an issue uncovered when building an application using the GLUT_BITMAP_* constants under the Nintendo Wii: freeglut_std.h was defining these constants to point to the variables defined in the X11 font module.
We fix this by checking for the presence of the __DEVKITPRO__ macro, which is a macro always defined when using the GCC built by the devkitPro distribution. Since this is a distribution meant for gaming consoles, we can be sure that X11 is not available there, so let's use the fonts embedded in freeglut.
=> freeglut_std.h: don't use X11 fonts when building with devkitPro

progs/demos/Lorenz/lorenz.c
Only call OpenGL functions after glutInit/glutCreateWindow.
In Cocoa the OpenGL context is only created during windows creation (glutCreateWindow)
=> macOS: Update Lorenz demo to run on macOS (Cocoa)

include/GL/freeglut_ext.h, src/egl/fg_init_egl.c, src/egl/fg_init_egl.h, src/fg_gl2.c, src/fg_gl2.h, src/fg_internal.h, src/fg_structure.c
Removes these types of warnings:
- `warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]`
Test builds ran:
- `CFLAGS="-Wall -Wpedantic"  cmake -DCMAKE_BUILD_TYPE=Debug .. && make clean && make`
- `CFLAGS="-std=gnu89 -Wall -Wpedantic" cmake -DCMAKE_BUILD_TYPE=Debug .. && make clean && make`
=> build: remove strict-prototype warnings

src/cocoa/fg_display_cocoa.m, src/cocoa/fg_internal_cocoa.h, src/cocoa/fg_window_cocoa.m
Add display synchronization for macOS using CVDisplayLink to properly time buffer swaps with screen refresh. Implements thread synchronization with mutex/condition variables and configures the display link callback for windows with double buffering.
See PR #204 for demonstration
=> cocoa: Implement VSync with CVDisplayLink

progs/demos/smooth_opengl3/smooth_opengl3.c
- Added macOS-specific OpenGL header inclusion with FREEGLUT_NO_GL_INCLUDE define
- Updated shader version from 140 to 150 and OpenGL context version from 3.1 to 3.2 (OpenGL 3.1 not supported on macOS)
- Added GLUT_CORE_PROFILE to context initialization
- Removed some ^M line endings
Note requires PR #198
=> macOS: Update smooth_opengl3 demo to run on macOS

src/cocoa/fg_init_cocoa.m, src/cocoa/fg_window_cocoa.m
This includes two changes:
OpenGL uses `(0,0)` as the bottom-left corner, whereas Cocoa uses the
top-left. Adjust coordinate origin to match OpenGL’s screen-space
convention.
Use `[NSScreen visibleFrame]` instead of `[NSScreen frame]`.
This excludes the macOS menu bar and dock from the reported screen dimensions
Add official VSync support for macOS via fallback mechanisms. Since the
official VSync support via swapInterval has been unreliable across
recent macOS releases (as OpenGL is deprecated on the platform), this
implementation still uses CVDisplayLink as the primary approach. The code allows for easy switching to the official swapInterval method
if/when Apple's OpenGL implementation stabilizes.
=> Macos improve window handling

.github/workflows/build_macosx_cocoa.yml, .github/workflows/build_macosx_x11.yml
This PR includes:
- [CI: Enable building demo applications on macOS (X11)](https://github.com/freeglut/freeglut/commit/abca9e871f7301697064bdc037815cea0ee4ac0e)
- [CI: Enable new macOS Cocoa build](https://github.com/freeglut/freeglut/commit/8a4f3705f056c3f34022fb92e4bcac3787829b41)
This fixes #212
=> Update GitHub actions for macOS

src/cocoa/fg_state_cocoa.m, src/cocoa/fg_window_cocoa.m
- Implements fgPlatformGlutDeviceGet to report keyboard/mouse availability and buttons
- Implements fgPlatformGlutGet with comprehensive support for window properties
- Adds placeholder for fgPlatformGlutGetModeValues with NO_IMPL marker
- Adds TODO comment for refactoring pixel format creation logic to support GLUT_DISPLAY_MODE_POSSIBLE
part of #195
Tested with this sample application:
```c
#include <GL/freeglut.h>
#include <stdio.h>
void display() {
glClear(GL_COLOR_BUFFER_BIT);
printf("GLUT_WINDOW_X: %d\n", glutGet(GLUT_WINDOW_X));
printf("GLUT_WINDOW_Y: %d\n", glutGet(GLUT_WINDOW_Y));
printf("GLUT_WINDOW_BORDER_WIDTH: %d\n", glutGet(GLUT_WINDOW_BORDER_WIDTH));
printf("GLUT_WINDOW_HEADER_HEIGHT: %d\n", glutGet(GLUT_WINDOW_HEADER_HEIGHT));
printf("GLUT_WINDOW_WIDTH: %d\n", …
```
=> Cocoa: implement fgPlatformGlutDeviceGet and fgPlatformGlutGet

src/cocoa/fg_window_cocoa.m, src/fg_init.c
FreeGLUT’s glutInitDisplayString support currently parses only display modes, not criteria as specified in the full GLUT spec. This PR begins addressing that limitation.
This includes the following commits:
1. **init: fix "aux" token in display string parser**
- Rename "aux" to "auxbufs" in the Tokens[] array for consistency with the
documented token name.
2. **init: add "=N"”parsing for `samples` and `auxbufs`**
- Introduce `parseCriteria()` helper (ported from classic GLUT) plus
`Comparison`/`Criterion` types to interpret numeric criteria.
- `glutInitDisplayString()` now recognises the forms `samples=N` and
`auxbufs=N`, setting `fgState.SampleNumber` and
`fgState.AuxiliaryBufferNumber` respectively.
3. **Cocoa: honor auxbufs=N and samples=N when building the NSOpenGL pixel‑format**
=> init: Improve display string parsing

src/cocoa/fg_window_cocoa.m
tl;dr - Use explicit NSOpenGLContext creation on macOS
On macOS, the implicit `NSOpenGLContext` creation by `NSOpenGLView` could lead to a timing issue where the context was not yet associated with a ready drawable surface.
This would cause an incorrect state after `glutCreateWindow` returned, but before the first `reshape` or `display` callbacks were invoked. In this window, queries like `GL_DRAW_BUFFER` would incorrectly return `GL_NONE` (0). The issue was masked and corrected by subsequent callbacks in the main loop.
This change refactors the context creation to be explicit:
1.  The `fgOpenGLView` is created without an `NSOpenGLPixelFormat`.
2.  The `NSOpenGLContext` is created manually with the desired pixel format.
3.  The context is explicitly associated with the view using …
=> cocoa: fix incorrect draw buffer state after window creation

CMakeLists.txt, progs/demos/accum/accum.c
Add a minimal interactive demo showing accumulation buffer usage for motion blur effects. Features a rotating line/cross with configurable parameters including rotation speed, line dimensions, accumulation passes, and rendering options.
=> demos: add accumulation buffer motion blur example
